name: my-workflow
on: 
    push:
        branches:
            - main
            - dev
    pull_request:
        types: [opened, closed]
        branches: [main, dev]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Lint code
              run: npm lint code
            - name: Run tests
              run: npm run test
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: test.json
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Build code
              run: npm run build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the code
              run: echo ${{github.event}}
    report:
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: test-report
                path: test.json